language: node_js
node_js:
- '8'
deploy:
  provider: npm
  email: supersnager@gmail.com
  api_key:
    secure: usjKWD+I4HQFEyF79Mnc+wTJTFCDcJZCxvoXRFji8GUzQo/zE6z660EP7DFGMn9KV0PCXxfehTGBsibKBQQSkIaXA7FjJakyXYS62QNh8aT8e1/iguexBHvAV/YJUxPU56TBDllygmRUv13wPW+mpgx+TbI0dXC+g2pjzvvLg7Yn7lA54ws7ctaH/dC//IOedR0bFLfm+JZ5FqSZPtFFvhFhAo/r5WyZenvsOG2rCt3/4HyUtJv2F8V2DCkK3Fe8+p0KOKEhnNclCkPfpF9XUIkNd0bXVZZMmmY8yqvEQQK+N9p+CjSJ+kxSYg/1Hhr39vwNoFCymdsP6/qCflhiL7HZr4GAaHNpGUHRJvYT+7FL2qR9pHU5bHZb64wpm+IylJ7RE2gIBn6PVtT+qr49Hklctaw7f2upM5utPuNVgj/VZtUx4NP06FAmYHev1zKiAo3vYN5rWWYvzjPM4evC4EJAHgryCSdYK3/KbQtN+TLZclH0e665SWxucbGcz9qh+R/cMuIl+TL1dtvKbNo4EzN2CLPJUQjxjhldCrZnXo/m3CDNRsMW+BEsO8YvSbYhoLlBGhZHQs6SD57UrCdZPxRnNd3TKKm1ZlaNJS9bscKyLT2f/f+uGZBaYvGUQeVKx7+Q0a+zu+4tigQsLkOi/1BrrjmXWJiSiufem05GR1I=
  skip_cleanup: true
  on:
    tags: true
    branch: master
